-- Oracle DDL (dev local)
CREATE TABLE weather_user.weather_api_response (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location VARCHAR2(200),
  api_type VARCHAR2(50),
  request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  json_data CLOB
);


